<?php

namespace Database\Seeders;

use App\Models\Elevator;
use Illuminate\Database\Seeder;

class ElevatorSeeder extends Seeder
{
    public function run(): void
    {
        $elevators = [
            [
                'model' => 'MRL-320',
                'manufacturer' => 'WIPRO',
                'capacity' => 320,
                'persons' => 4,
                'cabin_width' => 1000,
                'cabin_depth' => 1000,
                'cabin_height' => 2100,
                'shaft_width' => 1400,
                'shaft_depth' => 1550,
                'pit_depth' => 1100,
                'overhead' => 3500,
                'speed' => 1.0,
                'drive_type' => 'MRL elektryczny',
                'max_stops' => 8,
                'base_price' => 65000.00,
                'description' => 'Dźwig osobowy MRL 320 kg, 4 osoby. Napęd elektryczny bez maszynowni. Idealny dla mniejszych budynków.',
                'is_active' => true,
            ],
            [
                'model' => 'MRL-450',
                'manufacturer' => 'WIPRO',
                'capacity' => 450,
                'persons' => 6,
                'cabin_width' => 1100,
                'cabin_depth' => 1400,
                'cabin_height' => 2100,
                'shaft_width' => 1550,
                'shaft_depth' => 1900,
                'pit_depth' => 1100,
                'overhead' => 3500,
                'speed' => 1.0,
                'drive_type' => 'MRL elektryczny',
                'max_stops' => 10,
                'base_price' => 72000.00,
                'description' => 'Dźwig osobowy MRL 450 kg, 6 osób. Napęd elektryczny bez maszynowni.',
                'is_active' => true,
            ],
            [
                'model' => 'MRL-630',
                'manufacturer' => 'WIPRO',
                'capacity' => 630,
                'persons' => 8,
                'cabin_width' => 1100,
                'cabin_depth' => 1400,
                'cabin_height' => 2100,
                'shaft_width' => 1600,
                'shaft_depth' => 1950,
                'pit_depth' => 1200,
                'overhead' => 3600,
                'speed' => 1.6,
                'drive_type' => 'MRL elektryczny',
                'max_stops' => 15,
                'base_price' => 85000.00,
                'description' => 'Dźwig osobowy MRL 630 kg, 8 osób. Prędkość 1,6 m/s. Standardowy model dla budynków wielorodzinnych.',
                'is_active' => true,
            ],
            [
                'model' => 'MRL-800',
                'manufacturer' => 'WIPRO',
                'capacity' => 800,
                'persons' => 10,
                'cabin_width' => 1350,
                'cabin_depth' => 1400,
                'cabin_height' => 2200,
                'shaft_width' => 1850,
                'shaft_depth' => 1950,
                'pit_depth' => 1200,
                'overhead' => 3600,
                'speed' => 1.6,
                'drive_type' => 'MRL elektryczny',
                'max_stops' => 20,
                'base_price' => 98000.00,
                'description' => 'Dźwig osobowy MRL 800 kg, 10 osób. Wzmocniona kabina dla większych budynków.',
                'is_active' => true,
            ],
            [
                'model' => 'MRL-1000',
                'manufacturer' => 'WIPRO',
                'capacity' => 1000,
                'persons' => 13,
                'cabin_width' => 1600,
                'cabin_depth' => 1400,
                'cabin_height' => 2200,
                'shaft_width' => 2100,
                'shaft_depth' => 1950,
                'pit_depth' => 1400,
                'overhead' => 3800,
                'speed' => 1.6,
                'drive_type' => 'MRL elektryczny',
                'max_stops' => 25,
                'base_price' => 115000.00,
                'description' => 'Dźwig osobowy MRL 1000 kg, 13 osób. Duża kabina, wysoka prędkość.',
                'is_active' => true,
            ],
            [
                'model' => 'Hydrauliczny-630',
                'manufacturer' => 'WIPRO',
                'capacity' => 630,
                'persons' => 8,
                'cabin_width' => 1100,
                'cabin_depth' => 1400,
                'cabin_height' => 2100,
                'shaft_width' => 1600,
                'shaft_depth' => 1950,
                'pit_depth' => 1500,
                'overhead' => 3200,
                'speed' => 0.6,
                'drive_type' => 'MRL hydrauliczny',
                'max_stops' => 8,
                'base_price' => 78000.00,
                'description' => 'Dźwig osobowy hydrauliczny 630 kg, 8 osób. Prędkość 0,63 m/s. Cichy i ekonomiczny.',
                'is_active' => true,
            ],
            [
                'model' => 'Hydrauliczny-1000',
                'manufacturer' => 'WIPRO',
                'capacity' => 1000,
                'persons' => 13,
                'cabin_width' => 1600,
                'cabin_depth' => 1400,
                'cabin_height' => 2200,
                'shaft_width' => 2100,
                'shaft_depth' => 1950,
                'pit_depth' => 1800,
                'overhead' => 3200,
                'speed' => 0.6,
                'drive_type' => 'MRL hydrauliczny',
                'max_stops' => 8,
                'base_price' => 105000.00,
                'description' => 'Dźwig osobowy hydrauliczny 1000 kg. Duża nośność, płynna praca.',
                'is_active' => true,
            ],
        ];

        foreach ($elevators as $elevator) {
            Elevator::create($elevator);
        }
    }
}
